declare module '@env' {
  export const API_BASE_URL: string;
  export const REFRESH_TOKEN: string;
  export const USE_MOCK_API: string;
  export const APP_NAME: string;
  export const APP_VERSION: string;
  export const ENABLE_LIVENESS_CHECK: string;
  export const ENABLE_SELFIE_UPLOAD: string;
  export const ENABLE_DEV_SKIP_OPTIONS: string;
  export const OTP_TIMEOUT: string;
  export const LIVENESS_CHECK_DURATION: string;
  export const UPLOAD_TIMEOUT: string;
  export const PHONE_REGEX: string;
  export const OTP_LENGTH: string;
  export const ANIMATION_DURATION: string;
  export const DEBOUNCE_DELAY: string;
  export const MAX_FILE_SIZE: string;
  export const COMPRESSION_QUALITY: string;
  export const MIN_BLINK_COUNT: string;
  export const MIN_FACE_DETECTION_RATE: string;
  export const MAX_CONSECUTIVE_NO_FACE_FRAMES: string;
  export const FRAME_PROCESSING_INTERVAL: string;
  export const CHECK_DURATION: string;
}
